# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(modeltime)
    library(parsnip)
    library(prophet)
    library(recipes)
    library(workflows)
}
b <- board_url(list(eirgrid_model = "https://raw.githubusercontent.com/tighthead03/Irish-Electricity-Forecasting-Model-MLOps/main/pins-r/eirgrid_model/20250419T092408Z-4fa0a/"))
v <- vetiver_pin_read(b, "eirgrid_model", version = "20250419T092408Z-4fa0a")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
